spring.application.name=parriya-api
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.parriya.parriya_api.controller
server.port=4002

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/parriya
spring.datasource.driverClassName=com.mysql.jdbc.Driver

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.connection-test-query=SELECT 1
!------------------------------------
! SANTI
spring.datasource.username=root
spring.datasource.password=santi2004
spring.jpa.hibernate.ddl-auto=update

# Mercado Pago Sandbox Access Token
mercadopago.access.token=TEST-1854611417079213-061122-83569ab51a84f3e69cf26989eb27c514-18451877

! ALEJO
!spring.datasource.username=root
!spring.datasource.password=conejo100
!spring.jpa.hibernate.ddl-auto=update

